[build]
  command = "npx nuxt build"
  publish = ".output/public"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  
[functions]
  node_bundler = "esbuild"
  directory = ".output/server"

# Redirect all requests to the SPA
[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 